language: go
go:
  - "1.11"

env:
  global:
    - secure: "SkXFKcBjL7dh4cmesmYnq5gXQfsA53zPK9/ih0HRoaKRGcEGSsU4SIua5F4ohfxJIMtS19jSYL69wUw7Dnh4ATJPPcvY43y2TBclHze5hjSYpDzEy5INod7vf4PH0HJH7tm6o0Fg0F1d8NHoNWSWcJ/ZcAcNfwuEb0DkrblV/yAF3BemIjUSuIfA4wTIq93BW6Kdx1wV0OxTKq50EcGMlWtkgBqd0H/sJq4EP7rtdLpFsLeIyfb3k5xX+0ujh8cLn5sQ7dCV3gemZr52Qd0t4QZLG45SM2QLgtFovewzcnCBnfH372hyEdhSfOCmF8AmE642T4ovjWGk/1xREBR+bsgkGX1BsXkFhx9kgK9b1BRBowu/FyoTr9puXIbJbO7NqOsojo61Cj5mrAAh7RMhvg7kZciPwgxSZsdFBsJfUUACsQvnnOwY4iqjhIoAFWUg2/QoUMn/gc7qvXvzxNsOTMeeXliAXKW4vvvcS27cLR0LuAEo54IxnTGlq0P4sm8ltz3mA7yo4ucCSLd+hKQxhJVCgvWGnhufCLTa7qyD6CjbuFF/o+g143rQzH2v853PBrmzg/mfh+8vWBGYmtnTmQQqGt1qSYv1FxRCsj6lQOv5X6smM4W1VX1jHU1NruNcaFYsc8nZpr+K0KGTE/3JDeyuS14xQT3m2oyEm2gJVXo="

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  